# TRABAJO PRACTICO N°1
# --------------------------------PARTE 1--------------------------------
# 1. CREA UNA VARIABLE LLAMADA CONEJOS Y ASIGNARLE EL VALOR 126.
conejos = 126
# 2. CREA UNA VARIABLE LLAMADA ZANAHORIAS Y ASIGNALE EL VALOR 0.
zanahorias = 0
# 3. MUESTRA EL CONTENIDO DE LA VARIABLE CONEJOS.
print(conejos)
# 4. MODIFICA EL CONTENIDO DE LA VARIABLE CONEJOS POR 150.
conejos = 150
# 5. COPIA EL VALOR DE LA VARIABLE CONEJOS EN LA VARIABLE ZANAHORIAS.
zanahorias = conejos
# 6. IMPRIME EL VALOR DE LAS DOS VARIABLES CON PRINT().
print(f'zanahorias = {zanahorias} - conejos = {conejos}')
# 7. MODIFICA EL VALOR DE CONEJOS POR 250 Y VUELVE A MOSTRAR LAS DOS VARIABLES.
conejos = 250
print(f'zanahorias = {zanahorias} - conejos = {conejos}')
# --------------------------------PARTE 2--------------------------------
# 1. CALCULAR LAS SIGUIENTES OPERACIONES Y MUESTRA EN PANTALLA:
#   3  MAS 6
print(f' 3 + 6 = {3 + 6}')

#   5 MENOS 4
print(f' 5 - 4 = {5 - 4}')

#   6 MULTIPLICADO POR 8
print(f' 8 * 8 = { 8 * 8 }')

#   8 DIVIDIDO 2
print(f' 8 / 2 = {8 / 2}')

#   DIVISION ENTERA DE 6 DIVIDIDO 2
print(f' 6 // 2 = {6 // 2}')

#   3 MULTIPLICADO POR 5
print(f' 3 * 5 = { 3 * 5 }')

# 2. COLOCA LOS PARENTESIS EN SU LUGAR CORRESPONDIENTE PARA LA EXPRESION 4+5*6 DE LA FORMA QUE:
#   A. PYTHON REALICE PRIMERO LAS SUMAS.
print(f' (4+5)*6 = { (4+5)*6 }')

#   B. PYTHOM REALICE PRIMERO LAS MILTUPLICACIONES.
print(f' 4+(5*6) = { 4+(5*6) }')

# --------------------------------PARTE 3--------------------------------

# 1. ESCRIBE LA PALABRA ELEFANTE DENTRO DE UNA VARIABLE LLAMADA ANIMAL.
ANIMAL = "elefante"

# 2. ESCRIBE LA PALABRA ROSA DENTRO DE LA VARIABLE LLAMADA COLOR.
COLOR = "rosa"

# 3. CREA UNA VARIABLE LLAMADA IMAGINA DONDE SE ALMACENA LAS DOS VARIABLES ANTERIORES: ANIMAL Y COLOR DANDO COMO RESULTADO UN DATO DE TIPO STRING IGUAL A "ELEFANTE ROSA".
IMAGINA = ANIMAL+" "+COLOR
IMAGINA2 = f'{ANIMAL} {COLOR}'

# 4. PUNTO EXTRA: CONVERTIR EL CONTENIDO DE LA VARIABLE IMAGINA A MAYUSCULAS, UTILIZANDO UN METODO DE STRINGS
IMAGINA = IMAGINA.upper()
